name: telegram-to-dailymotion-bot
regions:
  - fra # Frankfurt region
services:
  - name: bot-service
    description: "Telegram to Dailymotion Bot Service"
    ports:
      - name: http
        port: 80
    routes:
      - name: main-route
        path: /*
    instances:
      - name: bot-instance
        type: container
        image: DOCKER_HUB_ACCOUNT/REPO_NAME:latest # Replace with your Docker Hub account and repository name
        ports:
          - name: http
            port: 80
        env:
          - name: BOT_TOKEN ''
          - name: DAILY_MOTION_CLIENT_ID
            value: ''
          - name: DAILY_MOTION_CLIENT_SECRET
            value: ''
          - name: DAILY_MOTION_USERNAME
            value: ''
          - name: DAILY_MOTION_PASSWORD
            value: ''
